services:
  backend:
    container_name: fastify
    build: ./backend
    image: fastify
    ports:
      - "3000:3000"
    volumes:
      - fastify_data:/app/database
    env_file:
      - .env
    networks:
      - ft_transcendence
    restart: always
    init: true
    tty: true

  # frontend:
  #   container_name: nginx
  #   build: ./frontend
  #   ports:
  #     - "443:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - ft_transcendence
  #   env_file:
  #     - .env
  #   restart: always
  #   init: true

volumes:
  fastify_data:
    name: fastify_data
    driver: local
    driver_opts:
      device: /Users/${LOGIN}/app/dev/tmp
      o: bind
      type: none


networks:
  ft_transcendence:
    driver: bridge
