services:
  backend:
    pull_policy: build
    build: ./backend
    image: backend
    container_name: backend
    # 포트 노출하지 않음 (nginx 프록시를 통해서만 접근)
    volumes:
      - ${DATA_PATH}:/app/database
      - ./backend/public:/app/public
    env_file:
      - ./backend/.env
    networks:
      - ft_transcendence
    restart: always
    init: true
    tty: true

  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    networks:
      - ft_transcendence
    env_file:
      - ./frontend/.env
    restart: always
    init: true

networks:
  ft_transcendence:
    driver: bridge
