CREATE TABLE IF NOT EXISTS user_2fa (
  user_id INTEGER PRIMARY KEY,
  two_fa_secret VARCHAR NOT NULL,
  is_enabled BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  -- updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
