CREATE TABLE IF NOT EXISTS user_profiles (
	user_id INTEGER PRIMARY KEY,
	name VARCHAR(10) UNIQUE NOT NULL,
	avatar VARCHAR,
	status BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (user_id) REFERENCES users(id)
);